name: walper
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.5 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  get:
  cupertino_icons: ^1.0.2
  flutter_screenutil: ^5.6.0
  flutter_svg: ^2.0.7
  pinput: ^2.2.31
  flutter_staggered_grid_view: ^0.7.0
  dropdown_button2:
  dot_navigation_bar: ^1.0.2
  flutter_advanced_drawer: ^1.3.5
  async_wallpaper: ^2.0.3
  flutter_cache_manager: ^3.3.1
  shared_preferences: ^2.2.0
  http:
  flutter_bloc: ^8.1.3
  flutter_rating_bar: ^4.0.1
  flutter_keyboard_visibility: ^5.4.1
  share_plus: ^7.0.2
  external_path: ^1.0.3
  image: ^4.0.17
  firebase_messaging: 14.2.1
  firebase_core: ^2.15.0
  flutter_local_notifications: ^15.1.0+1
  permission_handler: ^10.4.3
  image_gallery_saver: ^2.0.3
  path_provider: ^2.0.15
  google_sign_in: ^6.1.4
  firebase_auth: ^4.7.2
  lottie: ^2.5.0
  cached_network_image_builder:
  change_app_package_name: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.2

flutter:

  uses-material-design: true

  assets:
    - assets/images/png/
    - assets/images/jpg/
    - assets/images/svg/
    - assets/images/icons/
    - assets/lottie/

  fonts:
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto-Regular.ttf
          weight: 300